<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		
		<title>CVE-2019-20426 - Vulnerability Data</title>
		
		<link rel="shortcut icon" type="image/png" href="/favicon.ico" />
		<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-175514417-4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-175514417-4');
</script>

	</head>
<body>

<h2>Vulnerability Data</h2>
<h1>CVE-2019-20426</h1>
<p>In the Lustre file system before 2.12.3, the ptlrpc module has an out-of-bounds access and panic due to the lack of validation for specific fields of packets sent by a client. In the function ldlm_cancel_hpreq_check, there is no lock_count bounds check.</p>

<dl>
	<dt>Published</dt>
	<dd>2020-01-26</dd>

	<dt>Modified</dt>
	<dd>2020-01-26</dd>
</dl>

<h3>References</h3>
<ul>
	<li><a href="http://lustre.org/">MISC:http://lustre.org/</a></li>
<li><a href="http://wiki.lustre.org/Lustre_2.12.3_Changelog">MISC:http://wiki.lustre.org/Lustre_2.12.3_Changelog</a></li>
<li><a href="https://jira.whamcloud.com/browse/LU-12614">MISC:https://jira.whamcloud.com/browse/LU-12614</a></li>
<li><a href="https://review.whamcloud.com/#/c/36107/">MISC:https://review.whamcloud.com/#/c/36107/</a></li>
</ul>

<footer>
	<p><a href="https://reconmap.org">Track security vulnerabilities</a> with <strong>Reconmap</strong>.</p>
</footer>


</body>
</html>