<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		
		<title>CVE-2020-1627 - Vulnerability Data</title>
		
		<link rel="shortcut icon" type="image/png" href="/favicon.ico" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
		  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
		<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XL44S2GJJ7"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XL44S2GJJ7');
</script>
	</head>
<body>
	<div class="container">
	

  <nav>
    <div class="nav-wrapper">
      <div class="col s12">
        <a href="https://www.vulnerabilitydata.com" class="breadcrumb">Vulnerability Data</a>
        <a href="/2020" class="breadcrumb">2020</a>
        <a href="#" class="breadcrumb">CVE-2020-1627</a>
      </div>
    </div>
  </nav>

<h2>Vulnerability Data</h2>
<h1>CVE-2020-1627</h1>
<p>A vulnerability in Juniper Networks Junos OS on vMX and MX150 devices may allow an attacker to cause a Denial of Service (DoS) by sending specific packets requiring special processing in microcode that the flow cache can't handle, causing the riot forwarding daemon to crash. By continuously sending the same specific packets, an attacker can repeatedly crash the riot process causing a sustained Denial of Service. Flow cache is specific to vMX based products and the MX150, and is enabled by default in performance mode. This issue can only be triggered by traffic destined to the device. Transit traffic will not cause the riot daemon to crash. When the issue occurs, a core dump and riot log file entry are generated. For example: /var/crash/core.J-UKERN.mpc0.1557255993.3864.gz /home/pfe/RIOT logs: fpc0 riot[1888]: PANIC in lu_reorder_send_packet_postproc(): fpc0 riot[6655]: PANIC in lu_reorder_send_packet_postproc(): This issue affects Juniper Networks Junos OS: 18.1 versions prior to 18.1R3 on vMX and MX150; 18.2 versions prior to 18.2R3 on vMX and MX150; 18.2X75 versions prior to 18.2X75-D60 on vMX and MX150; 18.3 versions prior to 18.3R3 on vMX and MX150; 18.4 versions prior to 18.4R2 on vMX and MX150; 19.1 versions prior to 19.1R2 on vMX and MX150. This issue does not affect Junos OS versions prior to 18.1R1.</p>

<dl>
	<dt>Published</dt>
	<dd>2020-04-08</dd>

	<dt>Modified</dt>
	<dd>2020-04-09</dd>
</dl>

<h3>References</h3>
<ul>
	<li><a href="https://kb.juniper.net/JSA11006">CONFIRM:https://kb.juniper.net/JSA11006</a></li>
</ul>

<footer>
	<p><a href="https://reconmap.org">Track security vulnerabilities</a> with <strong>Reconmap</strong>.</p>
</footer>


	</div>
</body>
</html>