<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		
		<title>CVE-2020-15720 - Vulnerability Data</title>
		
		<link rel="shortcut icon" type="image/png" href="/favicon.ico" />
		<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-175514417-4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-175514417-4');
</script>

	</head>
<body>

<h2>Vulnerability Data</h2>
<h1>CVE-2020-15720</h1>
<p>In Dogtag PKI through 10.8.3, the pki.client.PKIConnection class did not enable python-requests certificate validation. Since the verify parameter was hard-coded in all request functions, it was not possible to override the setting. As a result, tools making use of this class, such as the pki-server command, may have been vulnerable to Person-in-the-Middle attacks in certain non-localhost use cases. This is fixed in 10.9.0-b1.</p>

<dl>
	<dt>Published</dt>
	<dd>2020-07-14</dd>

	<dt>Modified</dt>
	<dd>2020-07-14</dd>
</dl>

<h3>References</h3>
<ul>
	<li><a href="https://bugzilla.redhat.com/show_bug.cgi?id=1855273">MISC:https://bugzilla.redhat.com/show_bug.cgi?id=1855273</a></li>
<li><a href="https://github.com/dogtagpki/pki/commit/50c23ec146ee9abf28c9de87a5f7787d495f0b72">MISC:https://github.com/dogtagpki/pki/commit/50c23ec146ee9abf28c9de87a5f7787d495f0b72</a></li>
<li><a href="https://github.com/dogtagpki/pki/compare/v10.9.0-a2...v10.9.0-b1">MISC:https://github.com/dogtagpki/pki/compare/v10.9.0-a2...v10.9.0-b1</a></li>
</ul>

<footer>
	<p><a href="https://reconmap.org">Track security vulnerabilities</a> with <strong>Reconmap</strong>.</p>
</footer>


</body>
</html>